# EXP

DICKY_START_EXP = 1000

NORMAL_COIN_EXP = 70
GOT_SLAP_EXP = 14

HIGH_COIN_EXP = 110
GAIN_ITEM_EXP = 60
LOST_ITEM_EXP = 0



# ITEMS

TOTAL_ITEMS = 12

SWEATBAND = 0
TOILET_WATER = 1
SLIGHLY_OVERCOOKED_PITA = 2
COUPON_FOR_REE_GYROS = 3
DOGGY_DICE = 4
ROLEKS_CATALOG = 5
STRAY_HAIR_EXTENSION = 6
MARIAS_STYLING_GEL = 7
HOROSCOPE_CUTOUT = 8
LOTTERY_TICKET = 9
UNPAID_CLUB_TAB = 10
CANADA_GOOSE_VODKA = 11
LOOT_LOSS = 12

ITEM_NAME = {
    0: 'SWEATBAND',
    1: 'TOILET_WATER',
    2: 'SLIGHLY_OVERCOOKED_PITA',
    3: 'COUPON_FOR_REE_GYROS',
    4: 'DOGGY_DICE',
    5: 'ROLEKS_CATALOG',
    6: 'STRAY_HAIR_EXTENSION',
    7: 'MARIAS_STYLING_GEL',
    8: 'HOROSCOPE_CUTOUT',
    9: 'LOTTERY_TICKET',
    10: 'UNPAID_CLUB_TAB',
    11: 'CANADA_GOOSE_VODKA',
}

ITEM_LOOT_LOSS_RATE = {
    SWEATBAND: .15,
    TOILET_WATER: .14,
    SLIGHLY_OVERCOOKED_PITA: .12,
    COUPON_FOR_REE_GYROS: .11,
    DOGGY_DICE: .13,
    ROLEKS_CATALOG: .1,

    STRAY_HAIR_EXTENSION: .07,
    MARIAS_STYLING_GEL: .06,
    HOROSCOPE_CUTOUT: .05,
    LOTTERY_TICKET: .03,
    UNPAID_CLUB_TAB: .02,
    CANADA_GOOSE_VODKA: .02,
}

# ARENAS

TOTAL_ARENAS = 6

HANGOVER_HASTLE = 0
SOUVLAKI_SWINDLE = 1
FOUR_FINGER_FUMBLE = 2
CURL_UP_AND_DYE = 3
LIQUOR_AND_LATEX = 4
LIQUID_LOUNGE = 5

class AREANA_SELECTIONS(Enum):
    COIN_0 = 0
    COIN_1 = 1
    COIN_2 = 2
    ITEM_0 = 3
    ITEM_1 = 4
    ITEM_2 = 5

    COIN_PROBS = 6
    COIN_RANGES = 7

    ITEM_PROBS = 8
    ITEM_PRICES = 9

    LOOT_LOSS_PROB = 10
    MISSION_TIME = 11

ARENA_INFO = {
    HANGOVER_HASTLE: {
        AREANA_SELECTIONS.COIN_PROBS: [.288, .028, .384],
        AREANA_SELECTIONS.COIN_RANGES: [[5, 10], [50, 100], [8, 12]],
        AREANA_SELECTIONS.ITEM_PROBS: [.06, .03],
        AREANA_SELECTIONS.ITEM_PRICES: [35, 35],
        AREANA_SELECTIONS.LOOT_LOSS_PROB: .2,
        AREANA_SELECTIONS.MISSION_TIME: 4
    },

    SOUVLAKI_SWINDLE: {
        AREANA_SELECTIONS.COIN_PROBS: [.288, .028, .384],
        AREANA_SELECTIONS.COIN_RANGES: [[8, 14], [60, 120], [6, 12]],
        AREANA_SELECTIONS.ITEM_PROBS: [.054, .035],
        AREANA_SELECTIONS.ITEM_PRICES: [100, 85],
        AREANA_SELECTIONS.LOOT_LOSS_PROB: .2,
        AREANA_SELECTIONS.MISSION_TIME: 4
    },

    FOUR_FINGER_FUMBLE: {
        AREANA_SELECTIONS.COIN_PROBS: [.291, .019, .339],
        AREANA_SELECTIONS.COIN_RANGES: [[7, 14], [70, 140], [10, 16]],
        AREANA_SELECTIONS.ITEM_PROBS: [.05, .035],
        AREANA_SELECTIONS.ITEM_PRICES: [45, 145],
        AREANA_SELECTIONS.LOOT_LOSS_PROB: .25,
        AREANA_SELECTIONS.MISSION_TIME: 6
    },
    
    CURL_UP_AND_DYE: {
        AREANA_SELECTIONS.COIN_PROBS: [.291, .019, .339],
        AREANA_SELECTIONS.COIN_RANGES: [[10, 18], [80, 160], [8, 16]],
        AREANA_SELECTIONS.ITEM_PROBS: [.05, .035],
        AREANA_SELECTIONS.ITEM_PRICES: [185, 175],
        AREANA_SELECTIONS.LOOT_LOSS_PROB: .25,
        AREANA_SELECTIONS.MISSION_TIME: 6
    },

    LIQUOR_AND_LATEX: {
        AREANA_SELECTIONS.COIN_PROBS: [.291, .018, .291],
        AREANA_SELECTIONS.COIN_RANGES: [[12, 20], [90, 180], [9, 18]],
        AREANA_SELECTIONS.ITEM_PROBS: [.05, .035],
        AREANA_SELECTIONS.ITEM_PRICES: [685, 525],
        AREANA_SELECTIONS.LOOT_LOSS_PROB: .3,
        AREANA_SELECTIONS.MISSION_TIME: 8
    },
    
    LIQUID_LOUNGE: {
        AREANA_SELECTIONS.COIN_PROBS: [.291, .018, .291],
        AREANA_SELECTIONS.COIN_RANGES: [[10, 20], [100, 200], [12, 24]],
        AREANA_SELECTIONS.ITEM_PROBS: [.05, .035],
        AREANA_SELECTIONS.ITEM_PRICES: [1300, 1300], # estimated price
        AREANA_SELECTIONS.LOOT_LOSS_PROB: .3,
        AREANA_SELECTIONS.MISSION_TIME: 8
    },
}